### ISSUE TITLE
data too large for key size

### ISSUE THREAD

**Issue by hlogmans** [thekompanee/chamber#38]
I had a brilliant idea, using Chamber to contain also the SSL certificate & key encrypted, because I deploy with capistrano including Nginx setup.

But... When using a multiline YML-string, above error pops up. It is an OpenSSL error, because assymetric encryption should only be done on small data (mostly only a symmetric key). Did I overlook an option to make this possible with Chamber, or should I try to assemble a PR to do symmetric encryption for larger objects?

**Comment by jfelchner** [comment]
Nope there's no hidden option. I'm open to a PR though. :)

**Comment by hlogmans** [comment]
I'll give it a thought. There is a PKCS-format that does exactly this, but it adds quite some overhead. But standards in security are very valuable and OpenSSL supports this out of the box. But it is probably needed anyway because when I googled the errors, many people were running into this issue with Rails secret tokens that were too long...

**Comment by hlogmans** [comment]
See #39.

**Comment by jfelchner** [comment]
@hlogmans excellent! I'll refactor that and get it merged in a few days. 😄
