### ISSUE TITLE
latest version breaks Settings class

### ISSUE THREAD

**Issue by NekoNova** [thekompanee/chamber#40]
Hello,

Using the documentation, we have created a `Settings` class that extends Chamber.

```
class Settings
  extend Chamber
end
```

However, when we upgraded Chamber to 2.8, the following now happens/doesn't work anymore:

```
[24] pry(main)> Settings[:playground][:mailer]
=> {"address"=>"xxxxxx", "port"=>25, "authentication"=>"xxx", "enable_starttls_auto"=>false, "user_name"=>"xxxxxxxx", "password"=>"xxxxxxxxx"}
[25] pry(main)> Settings.env
NoMethodError: private method `env' called for Settings:Class
from /Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/chamber-2.8.0/lib/chamber.rb:31:in `method_missing'
```

Am I missing something?

**Comment by jfelchner** [comment]
@NekoNova thanks for the patience.  Things have been hectic around here the last few months.  Are you still having this issue?

**Comment by NekoNova** [comment]
will have to test this

**Comment by NekoNova** [comment]
Closing this as no longer relevant.
Successfully upgraded to latest version
