### ISSUE TITLE
Config files naming

### ISSUE THREAD

**Issue by bmedici** [thekompanee/chamber#46]
Hi,

Some projects I'm working on are based on this gem. I'm facing some problems though, probably caused by the great amount of magic everywhere.
When the project name contains an hyphen (let's say my-project), I cannon use Chamber.load files:["my-project.yml"] explicitely, as "project" will me considered as a namespace of "my".
We should be able to specify filenames directly that will not be expanded, parsed or anything.

Another nice thing would be to specify something else than "settings" as the basename. Setting it to the name of the project, along with a set of paths, would be great like:
paths:["/etc", "./", "/my/config/dir"], basename: "my-project"

As of today, it seems that this cold be achieved only with a config subdir and a settings.*.yml pattern.

Thanks!

**Comment by jfelchner** [comment]
@bmedici you are absolutely right about this in regards to the naming.  Unfortunately changing this would be a fairly large undertaking as well as a large breaking change.  I'm not exactly willing to do that at this point.

FWIW, I almost always either name my settings file `settings.yml` (the default) or add a `settings` directory where I have multiple files each containing one type of configuration.

Sorry I couldn't make this smoother for you!
