### ISSUE TITLE
Error due to mising module not being loaded

### ISSUE THREAD

**Issue by ghanima** [thekompanee/chamber#54]
## Current Behavior

When running chamber cli commands the following error appears
`rsa_key_passphrase': uninitialized constant Chamber::Commands::Initialize::SecureRandom (NameError)

The above error happes with both init argument and secure argument

This is the full error

      create  .chamber.pem
/usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/chamber-2.10.1/lib/chamber/commands/initialize.rb:134:in `rsa_key_passphrase': uninitialized constant Chamber::Commands::Initialize::SecureRandom (NameError)
Did you mean?  Chamber::Commands::Securable
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/chamber-2.10.1/lib/chamber/commands/initialize.rb:121:in `rsa_protected_key'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/chamber-2.10.1/lib/chamber/commands/initialize.rb:20:in `call'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/chamber-2.10.1/lib/chamber/commands/initialize.rb:63:in `call'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/chamber-2.10.1/lib/chamber/binary/runner.rb:134:in `init'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/chamber-2.10.1/bin/chamber:7:in `<top (required)>'
	from /usr/local/asdf/installs/ruby/2.4.1/bin/chamber:22:in `load'
	from /usr/local/asdf/installs/ruby/2.4.1/bin/chamber:22:in `<main>'

The error is pretty clear that it can't find a reference to a constant rsa_key_passphrase. From what I can tell there is code at line 124

  def rsa_key_passphrase
    @rsa_key_passphrase ||= SecureRandom.uuid
  end

However @rsa_key_passphrase is not set anyware in the code and SecureRandon belongs to the securerandom module which is not referenced anywhere in the code.

Adding require 'securerandom' 

Fixes the above error. 

This error is happening on a system with 
  - ruby 2.4.1
  - chamber 2.10.1

Can someone confirm if this is the appropriate approach?

### Steps to Reproduce 

1. When running chamber init command errors
2. Click "Current Orders"
3. Try to remove "Flux Capacitor" from the cart

**Comment by jfelchner** [comment]
@ghanima thanks for the patience, this'll get released in the next version :)
