### ISSUE TITLE
Chamber.keys behavior has changed

### ISSUE THREAD

**Issue by moofish32** [thekompanee/chamber#57]
## Current Behavior
Invoking Chamber.keys results in
```
(byebug) Chamber.keys
W, [2018-01-26T10:53:02.598532 #59303]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#display defined in Kernel. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
W, [2018-01-26T10:53:02.599175 #59303]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#display defined in Kernel. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
W, [2018-01-26T10:53:02.599651 #59303]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#display defined in Kernel. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
*** ArgumentError Exception: Invalid value for Boolean:
```

## Expected Behavior or New Behavior
return an array of known keys in chamber currently.

This appears to be with new release, but I get errors in many places for all versions > 2.10.2. 

Very good chance I grabbed a non-public API here, but curious if you could shed some light on the changes from 2.10.2 to 2.11+ so I can adjust as necessary.

Thanks for open sourcing your work.

**Comment by jfelchner** [comment]
@moofish The warnings are due to Hashie.  You can either change the name of your keys, or you can lock Hashie to a version lower than (I think) `0.50`

**Comment by jfelchner** [comment]
@moofish32 in the next version of Chamber I'll make that more explicit with an error message that describes exactly what's going on.

**Comment by jfelchner** [comment]
@moofish32 I was worried about this so I just went ahead and did this and released a new version for you. ;)

The new error message looks something like this:

```
We attempted to convert 'TEST_SETTING_GROUP_TEST_SETTING_ONE' from 'foo' to a 'Integer'.

Unfortunately, this did not go as planned.  Please either verify that your value is convertable
or change the original YAML value to be something more generic (like a String).

For more information, see https://github.com/thekompanee/chamber/wiki/Environment-Variable-Coercions
```

**Comment by moofish32** [comment]
@jfelchner -- thanks for the better error message. I'll try to resolve now. One question should empty string coerce to `false`?  That's now clearly my error. Sorry to comment on a closed issue (I don't think you need to reopen this issue). If we think a change is needed I'd rather spin out a new issue so it's clear to others.

**Comment by jfelchner** [comment]
@moofish32 `''` absolutely cannot be coerced to `false` because if you have `true` in your YAML and you don't set your ENV variable _at all_ (meaning that you _didn't_ want to overwrite your YAML, converting a `''` to `false` would overwrite your YAML value with `false`.
