### ISSUE TITLE
Namespaces in Rails are not resolved correctly

### ISSUE THREAD

**Issue by zpieslak** [thekompanee/chamber#58]
One more issue that that come out during the integration with Rails app. Currently I have it fixed within the app, but it would be nice to have it done inside the gem.

## Current Behavior

When using multiple files, with multiple key-pairs in Rails app, the keys are not loaded properly, which leads to `DecryptionFailure`.

### Steps to Reproduce 

Suppose I have two files with two-key pairs and I'm running `rails c` in `development` environment on host `myhostname`.

```
# File settings.yml

development:
  some_key: some_value

```
```
# File settings-myhostname.yml

development:
  some_other_key: some_other_value

```
The result is `DecryptionFailure` and rails console stops. But when I run `chamber show` it works fine, and the namespaces are resolved correctly.

## Expected Behavior or New Behavior

The rails app runs properly when changing [file](https://github.com/thekompanee/chamber/blob/master/lib/chamber/integrations/rails.rb#L9-L13) to 

`Chamber.load(basepath:   ::Rails.root.join('config'))`

**Comment by jfelchner** [comment]
@zpieslak thanks for the additional report! Can you create a `Rails new` with the minimal amount of stuff necessary to reproduce this?

**Comment by zpieslak** [comment]
@jfelchner Please find the repository [here](https://github.com/zpieslak/chamber-test). I put the instructions in README.

**Comment by jfelchner** [comment]
@zpieslak I'm going to knock this and your PR out next weekend.  Sorry for the delay!

**Comment by zpieslak** [comment]
@jfelchner OK, looking forward to see the results! I'm currently using own fork, but I would like to use your gem directly.

**Comment by jfelchner** [comment]
@zpieslak this was a MAJOR issue and I'm mad that it took me this long to get this fixed.  This will go out in the next release (probably later tonight).

Thanks again for reporting this (and the patience).
