### ISSUE TITLE
Q: Arbitrary Ruby Objects?

### ISSUE THREAD

**Issue by jrochkind** [thekompanee/chamber#59]
The [matrix comparing chamber to other similar gems](https://github.com/thekompanee/chamber/wiki/Gem-Comparison) has "Allowed Types" section, "Arbitrary Ruby Objects" check next to chamber. 

But I can't figure out how you'd provide "arbitrary ruby objects" as a chamber value via the yaml file?  Am I missing something, or misunderstanding what is meant by "arbitrary ruby objects"?

**Comment by jfelchner** [comment]
Thanks for the question @jrochkind.  It's built into the Ruby YAML parser so just follow any tutorial. :)

http://yaml.org/YAML_for_ruby.html#objects

**Comment by jrochkind** [comment]
oh that's what you meant? OK, thanks for info. 

I'm a bit skeptical that that's really going to work reliably with no pain for any arbitrary ruby object, but I'll play around with it maybe.
