### ISSUE TITLE
Default value when querying property

### ISSUE THREAD

**Issue by pmackay** [thekompanee/chamber#61]
## Current Problem
Is there a way to supply a default value when querying a property? 
e.g. in the way that ENV.fetch() can be used?

I have somewhat wondered if this could be an anti-pattern, as it scatters defaults across the code where the property is being fetched...

**Comment by jfelchner** [comment]
@pmackay firstly, all Chamber settings are just technically hashes, so you can do `::Chamber.env.foo.fetch('bar', 'baz')` just like you would with `ENV`.

Secondly, if you wanted defaults in one spot, I would use YAML's anchors to do this in the YAML file itself and not in code.

It's pretty easy to [configure defaults for your different namespaces](https://github.com/thekompanee/chamber/wiki/Defining-Settings#using-yamls-superpowers)

Let me know if you have any more questions!

**Comment by jfelchner** [comment]
Also, sorry for the delay on the reply!
