### ISSUE TITLE
CircleCI command not supported

### ISSUE THREAD

**Issue by pmackay** [thekompanee/chamber#62]
## Current Behavior
The [CircleCI wiki page](https://github.com/thekompanee/chamber/wiki/CircleCI) suggests 

`chamber circleci push --keys --api-token="1234567890"`

can be run but it says `Could not find command "circleci"`

### Steps to Reproduce

Run the command in shell.

## Expected Behavior

A key should upload to CircleCI.

## Environment

 - Device: 

 - OS:

    - [ ] Windows
    - [x] macOS
    - [ ] iOS
    - [ ] Android
    - [ ] Linux
    - [ ] Other

 - OS Version: Mojave

**Comment by jfelchner** [comment]
@pmackay This will be released as `2.13.0` shortly.  Please let me know if it works as expected. :)  And sorry for the delay!
