### ISSUE TITLE
Customising multiple namespaces…the right way

### ISSUE THREAD

**Issue by ideasasylum** [thekompanee/chamber#63]
## Current Behavior
The [wiki](https://github.com/thekompanee/chamber/wiki/Specifying-Multiple-Namespaces) currently suggests using this code

```ruby
Chamber.load( :basepath => Rails.root.join('config'),
              :namespaces => {
                :environment => ::Rails.env,
                :hostname    => ENV['HOST'] } )
```

but doesn't suggest _where_ that code should go. 

### Steps to Reproduce

I originally placed the code in an initializer but this introduced subtle bugs because the `environment/*.rb` files are loaded _before_ the `config/initializers/*`. This meant that any values I loaded from Chamber in `environments/production.rb` would come from the original loading of Chamber, performed by the `chamber.load` Railtie, without my custom hostname namespace.

Instead, what I ended up doing was adding a Railtie initializer to my `application.rb` to run after Chamber had loaded but before the environment files.

```ruby
module Podia
  class Application < Rails::Application
    # (re)load the Chamber configuration
    # We need to reload the Chamber configuration after the initial
    # chamber.load Railtie because Chamber uses the localhost name as
    # the hostname. We'd like to use the config domain.
    # This let's us use Chamber configuration in an environment .rb file
    # (unlike an initializer file in config/initializers which are loaded after)
    initializer 'podia.chamber', after: 'chamber.load', before: :load_environment_config do
      Chamber.load basepath: ::Rails.root.join('config'),
                   namespaces: {
                     environment: -> { ::Rails.env },
                     hostname:    -> { ENV['CONFIG_DOMAIN'] }
                   }
    end
  end
end
```

(though maybe I could even _replace_ the Chamber Railtie instead of reloading the config after the initial load 🤔)

I think maybe the wiki page should be updated with more context around when/where to load the custom namespace

**Comment by jfelchner** [comment]
@ideasasylum this is awesome!  I obviously didn't think about this use case when writing that wiki entry.  I'll update it with more information.

Thanks!

**Comment by jfelchner** [comment]
@ideasasylum I've added this to the wiki.  Just as a heads up, if I were you I'd _add_ the domain in the loader rather than overriding the hostname.  You can have as many namespaces as you want and if you leave the hostname in there, it will continue to allow individual developers to have their own local overridden settings.

```ruby
      Chamber.load basepath: ::Rails.root.join('config'),
                   namespaces: {
                     environment: -> { ::Rails.env },
                     domain:      -> { ENV['CONFIG_DOMAIN'] }
                     hostname:    -> { ::Socket.gethostname }
                   }
```

Thanks again!

**Comment by jfelchner** [comment]
@ideasasylum can you verify that:

```ruby
    initializer 'chamber.load', before: :load_environment_config do
      Chamber.load basepath: ::Rails.root.join('config'),
                   namespaces: {
                     environment: -> { ::Rails.env },
                     hostname:    -> { ENV['CONFIG_DOMAIN'] }
                   }
    end
```

also works?  I'm pretty sure that will stop Chamber from loading twice.

**Comment by ideasasylum** [comment]
yeah, I tried it on 2.12.3 and it still appears to load Chamber twice. I don't know you can replace an initializer that's already been loaded. At least, I haven't found a way

**Comment by jfelchner** [comment]
@ideasasylum Ok. That's unfortunate. 🙁  Thanks for replying back.
