### ISSUE TITLE
Chamber isn't encrypting but is removing the quotes around strings

### ISSUE THREAD

**Issue by Chrisgo-75** [thekompanee/chamber#65]
## Current Behavior
I have a Rails engine that I am upgrading from Rails 4.2 to Rails 5.2 and Chamber is no longer encrypting the variables within settings.yml

I have made a simple Rails engine that shows what is happening if you were to run "chamber secure".

Repo of Rails Engine representing the issue  
`git clone https://carndt1450@bitbucket.org/carndt1450/fivetwo.git`

### Steps to Reproduce

1. Run "chamber secure" from Engine root directory.
2. Output says it encrypted the strings but just removes the quotes.

## Expected Behavior
I would expect that "_secure_x" and "_secure_y" from both development and test would be encrypted.

## Environment

 - Device: Ubuntu 16.04 LTS

- Rails `-v5.2`

**Comment by jfelchner** [comment]
@Chrisgo-75 a repro repo helps out a ton! Thanks! 🙏

I'll take a look at this in the next week-ish and see what I can see. :)

Sorry about the trouble!

**Comment by Chrisgo-75** [comment]
Was able to solve the issue by placing `.chamber.pub.pem` into `/spec/dummy/`.

**Comment by jfelchner** [comment]
@Chrisgo-75 yes, the dummy dir is the root of the project for the dummy app and therefore that's where the keys need to be placed.
