### ISSUE TITLE
how to use with Heroku alternatives such as Dokku / Flynn?

### ISSUE THREAD

**Issue by aspiers** [thekompanee/chamber#66]
Congratulations on a great project!  I only just discovered it, and am very impressed by the quality of the design and documentation, and glad that someone had the sense and courage to point out the flaws in the 12-factor approach to configuration.  Not sure how they managed to conclude that overloading the environment was a good idea ... oh well.

Anyway, [the Heroku support](https://github.com/thekompanee/chamber/wiki/CLI-chamber-heroku) looks great, but would it be possible to get some hints on how to use Chamber with cheaper alternatives to Heroku, such as [Dokku](http://dokku.viewdocs.io/dokku/) or [Flynn](https://flynn.io/)?  If I had some pointers, I could perhaps help to write a wiki page documenting that properly, or maybe even propose some code extending Chamber to support Dokku.

For example [Dokku has strong support for environment variables](http://dokku.viewdocs.io/dokku/configuration/environment-variables/), so could that be used to pass the private key, similarly to [option 1 of the Heroku integration](https://github.com/thekompanee/chamber/wiki/Heroku#option-1-push-your-private-key)?

What about if I had a single git repo which I wanted to use to deploy the same codebase to multiple deployments within Dokku, each using a different set of secret credentials and other options, some being for dev/test/staging and others for production?  For example, I might have the following environments:

- development
- customer1-staging
- customer1-production
- customer2-staging
- customer2-production

each with different secret credentials, and some options specific to development / staging / production, and other options specific to a particular host.  I know I can achieve this in Chamber with namespaces, but I'm not sure how a deployment via Dokku would know which namespaces to use.

Any hints or pointers very gratefully received - thanks!

**Comment by jfelchner** [comment]
@aspiers thank you for the kind words ☺

For your first question, the answer lies on [this wiki page](https://github.com/thekompanee/chamber/wiki/Loading-Keys-From-Environment-Variables)

You just have to define an environment variable with the private key, and Chamber will pick it up automatically.

For your second question, in order to load specific namespaces at runtime based on other custom logic, you'd [do something like this](https://github.com/thekompanee/chamber/wiki/Custom-Namespaces).
