### ISSUE TITLE
All builds failing in Travis CI

### ISSUE THREAD

**Issue by mobilutz** [thekompanee/chamber#69]
I was wandering, why almost all of `chambers` builds are failing on Travis CI:
https://travis-ci.org/thekompanee/chamber/branches

I think it is, because there are some settings missing on Travis.
I wonder, why you use a CI, that does not run at all.

Not that you understand me incorrectly, I do very much like `chamber`, I am concerned that a 🔴 CI will be interpreted by some people that this gem is not safe to use.

**Comment by benkoshy** [comment]
Travis are now charging for Open Source projects - this might be the reason why?. 

It might be better for Chamber to switch over to Github actions for their CI builds.

**Comment by jfelchner** [comment]
I'm going to be switching to Github actions this week. ;)

**Comment by jfelchner** [comment]
@mobilutz alas there is only so much time in the day. :) Build status aside, the gem works as expected with the exception of a large issue running it on Rails 6 which I am about to rectify.  The first step was getting the repo on Github Actions which has just been accomplished.  Once the Heroku rate limit drops down, the build will be passing.
