### ISSUE TITLE
Possible upgrade of `thor` dependency?

### ISSUE THREAD

**Issue by mobilutz** [thekompanee/chamber#73]
## Current Problem

We cannot update our development dependency `license_finder` right now, as their `thor` dependency collides with the `thor` dependency from chamber.

license_finder:
https://github.com/pivotal/LicenseFinder/blob/master/license_finder.gemspec#L48

chamber:
https://github.com/thekompanee/chamber/blob/master/chamber.gemspec#L32

## Potential Solution or New Behavior
Upgrade chamber, to work with `thor` >= 1.0.1

I didn't find time yet, to look if maybe chamber is working out of the box with `thor >= 1.0.1`, maybe I will find some time in the future.

**Comment by mobilutz** [comment]
I created a small repo, showing the problem:
https://github.com/mobilutz/chamber-license_finder-bug

**Comment by jfelchner** [comment]
@mobilutz I will definitely update this to fix it to work with later versions of `thor`.  If I remember there was a backwards incompatible change, but at this point there's no reason I should be using such an old version.  I just haven't had time to update the gem.

Thank you for bringing it to my attention.

**Comment by jfelchner** [comment]
This is going out in the next release.  It will be compatible with the same `thor` versions as Rails is: https://github.com/thekompanee/chamber/blob/master/chamber.gemspec#L34

**Comment by jfelchner** [comment]
`chamber` `2.14.0` has been released: https://rubygems.org/gems/chamber/versions/2.14.0
