### ISSUE TITLE
Allow Wiki to be editable by the public

### ISSUE THREAD

**Issue by benkoshy** [thekompanee/chamber#75]
Current Problem
--------------------------------------------------------------------------------

* Maintenance of documentation by repository owner may be onerous.
* Many individual developers may face problems/shortfalls in the documentation (with the utmost respect) which cannot be fixed via PRs, and are quite cumbersome to open up issues etc.

Potential Solution or New Behaviour
--------------------------------------------------------------------------------

* Open up the Wiki for editing by the public.  (Right now, the general public cannot edit the wiki).

Examples of Benefits:
--------------------------------------------------------------------------------

* The benefits are that improvements can be made without active management of the maintainer of this library:
* e.g. Given Github actions are now gaining traction over Travis etc. I could to add in a section in the documentation on how people can customise Chamber to work with Github actions. This might be helpful to many, with a minimal cost in resources for the maintainer.

**Comment by jfelchner** [comment]
Hey @benkoshy.  I'm not going to do that because I want to be able to approve changes prior to making them public, but feel free to attach the content you would like to an issue and I'll be happy to review and integrate into the Wiki!  I'll even add your username to the edit so you can get some good karma. :)

**Comment by benkoshy** [comment]
@jfelchner as soon as i get gihub actions working for my app I'll create the documentation for this repo (chamber)..... that might take some time......... before i can have another attempt at it.

**Comment by jfelchner** [comment]
@benkoshy feel free to look at the github actions in this repo.  I added builds and linting a few weeks ago.

**Comment by benkoshy** [comment]
@jfelchner 

Finally got around to doing this - apologies for the delay. Here is what I would have added to the Wiki under Github actions vs Travis etc:


If you want to use Chamber with Github Actions, and run tests which relies on chamber secrets, how would you do this? Here is an example which demonstrates the problem:

```ruby
# some test:
class UsersControllerTest < ActionDispatch::IntegrationTest
  test "some test" do
    get user_url(@user)    
  end
end


class UsersController < ApplicationController
  def show
    puts Chamber.dig!(:smtp_email, :mailhost)
    # how can github actions access this variable without
    # Chamber's secrets key being known to github?
  end
end
```

They trick is to let github know about your secret key - you can add it to your repository. Perhaps it's easier to just add it in manually for the moment - see this image on how to do it:


![image](https://user-images.githubusercontent.com/15097447/116834832-380a2380-ac03-11eb-9c42-6a347322a7f5.png)


Then, in your Github action, simply ensure that you set up the CHAMBER_KEY environment variable.:

```yml
# .github/workflows/
name: ci
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CHAMBER_KEY: "${{ secrets.CHAMBER_KEY }}" # make sure this is there
    # etc
```

**Comment by jfelchner** [comment]
Awesome!  I will add this soon!  ❤

**Comment by jfelchner** [comment]
Added! https://github.com/thekompanee/chamber/wiki/Github-Actions

Also gave you credit at the bottom of the page. :)
