### ISSUE TITLE
[Wiki] Incorrect flags for CLI

### ISSUE THREAD

**Issue by ideasasylum** [thekompanee/chamber#78]
The [wiki page for the CLI](https://github.com/thekompanee/chamber/wiki/CLI-Overview) lists options for `encryption-key` and `decryption-key`. This is incorrect. The actual flags are the plural `encryption-keys` and `decryption-keys`. The description also gives an example of `--keypair` which is not a valid option.

### Screenshot

<img width="921" alt="image" src="https://user-images.githubusercontent.com/14988/170673043-164826f4-dfb9-4181-984a-77b8dfb74250.png">

**Comment by jfelchner** [comment]
@ideasasylum thank you!  This must've gotten missed when I added multi-key support to chamber.  I'll leave this open and resolve this the next chance I get.

**Comment by jfelchner** [comment]
Finally fixed!  Thank you!
