### ISSUE TITLE
CircleCI push integration ArgumentError

### ISSUE THREAD

**Issue by Guv0** [thekompanee/chamber#81]
Current Behavior
--------------------------------------------------------------------------------
ArgumentError initializing the CircleCI adapter when running `chamber circleci push --keys --username='myghuser' --project='myreponame' --api-token="1234567890"`: 

`unknown keywords: :rootpath, :namespaces, :shell (ArgumentError)`

### Steps to Reproduce

Run `chamber circleci push --keys --username='myghuser' --project='myreponame' --api-token="1234567890"` with valid args

Expected Behavior
--------------------------------------------------------------------------------
Key pushed to CircleCI and stored as an environment variable in the correct project.

Environment
--------------------------------------------------------------------------------
  * OS: MacOS

  * OS Version: Monterey 12.6.1

**Comment by jfelchner** [comment]
Hey @Guv0, the CircleCI-specific implementations are going to be removed in Chamber 3.0.  Please see [the new way](https://github.com/thekompanee/chamber/wiki/Loading-Keys-From-Environment-Variables) instead.  For rationale, you can look [here](https://github.com/thekompanee/chamber/wiki/Upgrading-To-Chamber-3.0#removal-cloud-settings-integrations).

I'd love a PR on making the CircleCI section of that page better!

**Comment by jfelchner** [comment]
@pmackay sorry for the delay. Something like this should work in your `circle.yml` file:

```yaml
  post:
machine:
  environment:
    CONTINUOUS_INTEGRATION: true
    - "echo 'IFS=\"|\" && export CHAMBER_KEY=\"$(echo -e $CHAMBER_KEY)\"' >> .circlerc"
```
