### ISSUE TITLE
Not all impelemntations of system grep support --colour flag

### ISSUE THREAD

**Issue by wscourge** [thekompanee/chamber#82]
### Steps to Reproduce

Run `chamber secure` on `ruby:3.2.0-alpine` docker image. Results:

```
$ bundle exec chamber secure
grep: unrecognized option: colour=never
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.
Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A|B|C N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...
Search for PATTERN in FILEs (or stdin)
	-H	Add 'filename:' prefix
	-h	Do not add 'filename:' prefix
	-n	Add 'line_no:' prefix
	-l	Show only names of files that match
	-L	Show only names of files that don't match
	-c	Show only count of matching lines
	-o	Show only the matching part of line
	-q	Quiet. Return 0 if PATTERN is found, 1 otherwise
	-v	Select non-matching lines
	-s	Suppress open and read errors
	-r	Recurse
	-R	Recurse and dereference symlinks
	-i	Ignore case
	-w	Match whole words only
	-x	Match whole lines only
	-F	PATTERN is a literal (not regexp)
	-E	PATTERN is an extended regexp
	-m N	Match up to N times per file
	-A N	Print N lines of trailing context
	-B N	Print N lines of leading context
	-C N	Same as '-A N -B N'
	-e PTRN	Pattern to match
	-f FILE	Read pattern from file
```

### Screenshot

![image](https://user-images.githubusercontent.com/16985871/213118824-05997c36-bac1-4163-a971-976ccbc4ad29.png)

Expected Behavior
--------------------------------------------------------------------------------
There should be no error.

Environment
--------------------------------------------------------------------------------
`ruby:3.2.0-alpine` docker image
```
$ uname -a
Linux b8821cbeff3b 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 Linux
```

**Comment by wscourge** [comment]
It is possible to simply `apk add grep` or `apk add --no-cache --upgrade grep`. [Turns out this is due to the **BusyBox** and not **apk** `grep` implementation](https://stackoverflow.com/q/70797180/6439240).

Anyway, its always good to steer clear of system dependencies.

**Comment by jfelchner** [comment]
Closing this in favor of #83.
